version: '3'

services:
  newsnow:
    image: ghcr.io/ourongxing/newsnow:latest
    container_name: newsnow
    restart: always
    ports:
      - '4444:4444'
    environment:
      - G_CLIENT_ID=Ov23liD5OCkzkE6XsyPJ
      - G_CLIENT_SECRET=b8138abb01dfac10705ee2c0cc5802ffb64aa624
      - JWT_SECRET=b8138abb01dfac10705ee2c0cc5802ffb64aa624
      - INIT_TABLE=true
      - ENABLE_CACHE=true
